import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import { ReportItem, ReportType } from '../types';
import { generateSignedReportPDF } from '../utils/pdfGenerator';
import {
  FileSpreadsheet,
  Download,
  Printer,
  Sparkles,
  PlusCircle,
  FileText,
  Building,
  CheckCircle2,
  X,
  FileDown,
  Sliders,
  BarChart3,
  Table,
  CheckSquare,
  Square,
  Eye,
  ShieldCheck,
  FileCheck2,
} from 'lucide-react';

interface PrintOptions {
  includeLetterhead: boolean;
  includeMetadata: boolean;
  includeAISummary: boolean;
  includeVisualCharts: boolean;
  includeSectorTables: boolean;
  includeSchemeLedger: boolean;
  includeSignatory: boolean;
}

export const ReportsPage: React.FC = () => {
  const { reports, departments, generateReport, financialYear, addToast, budgets, expenditures } = useApp();
  const { user } = useAuth();

  const [selectedReport, setSelectedReport] = useState<ReportItem | null>(null);
  const [reportType, setReportType] = useState<ReportType>('MONTHLY_UTILIZATION');
  const [departmentName, setDepartmentName] = useState('All Departments');
  const [isGenerating, setIsGenerating] = useState(false);

  // Print Options Configuration State
  const [showPrintOptions, setShowPrintOptions] = useState<boolean>(true);
  const [printOptions, setPrintOptions] = useState<PrintOptions>({
    includeLetterhead: true,
    includeMetadata: true,
    includeAISummary: true,
    includeVisualCharts: true,
    includeSectorTables: true,
    includeSchemeLedger: true,
    includeSignatory: true,
  });

  const togglePrintOption = (key: keyof PrintOptions) => {
    setPrintOptions(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const applyPrintPreset = (preset: 'ALL' | 'CHARTS_ONLY' | 'TABLES_ONLY' | 'EXECUTIVE_BRIEF') => {
    if (preset === 'ALL') {
      setPrintOptions({
        includeLetterhead: true,
        includeMetadata: true,
        includeAISummary: true,
        includeVisualCharts: true,
        includeSectorTables: true,
        includeSchemeLedger: true,
        includeSignatory: true,
      });
    } else if (preset === 'CHARTS_ONLY') {
      setPrintOptions({
        includeLetterhead: true,
        includeMetadata: true,
        includeAISummary: true,
        includeVisualCharts: true,
        includeSectorTables: false,
        includeSchemeLedger: false,
        includeSignatory: true,
      });
    } else if (preset === 'TABLES_ONLY') {
      setPrintOptions({
        includeLetterhead: true,
        includeMetadata: true,
        includeAISummary: false,
        includeVisualCharts: false,
        includeSectorTables: true,
        includeSchemeLedger: true,
        includeSignatory: true,
      });
    } else if (preset === 'EXECUTIVE_BRIEF') {
      setPrintOptions({
        includeLetterhead: true,
        includeMetadata: true,
        includeAISummary: true,
        includeVisualCharts: true,
        includeSectorTables: true,
        includeSchemeLedger: false,
        includeSignatory: true,
      });
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);

    try {
      const newRep = await generateReport({
        reportType,
        financialYear,
        departmentName: departmentName === 'ALL' ? 'All Departments' : departmentName,
        generatedBy: user?.name || 'Authorized Finance Officer',
      });
      setSelectedReport(newRep);
      addToast(
        'Dossier Generated',
        `Official dossier "${newRep.title}" compiled with AI executive summary.`,
        'SUCCESS'
      );
    } catch (e) {
      console.warn('Report generation failed:', e);
      addToast('Generation Error', 'Failed to generate financial dossier.', 'ERROR');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadCSV = (r: ReportItem) => {
    const headers = [
      'Report Title',
      'Report Type',
      'Department',
      'Financial Year',
      'Generated Date',
      'Generated By',
      'Revenue Outlay (Cr)',
      'Revenue Exp (Cr)',
      'Capital Outlay (Cr)',
      'Capital Exp (Cr)',
      'Executive Summary',
    ];

    const row = [
      `"${r.title.replace(/"/g, '""')}"`,
      `"${(r.reportType || '').replace(/_/g, ' ')}"`,
      `"${r.departmentName}"`,
      `"${r.financialYear}"`,
      `"${r.generatedAt}"`,
      `"${r.generatedBy}"`,
      '11200.0',
      '8450.0',
      '7250.0',
      '4760.0',
      `"${(r.aiExecutiveSummary || '').replace(/"/g, '""')}"`,
    ];

    const csvContent = headers.join(',') + '\n' + row.join(',') + '\n';
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `financial_report_${r.id || 'export'}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    addToast(
      'Report Export Complete',
      `Financial report "${r.title}" exported as CSV successfully.`,
      'SUCCESS'
    );
  };

  const handleExportFullLedgerCSV = () => {
    const headers = ['BudgetId', 'DepartmentId', 'SchemeName', 'Allocated (Cr)', 'Spent (Cr)', 'Quarter', 'Status'];
    const rows = budgets.map(b => [
      b.id,
      b.departmentId,
      `"${b.schemeName?.replace(/"/g, '""') || ''}"`,
      b.allocatedAmount,
      b.spentAmount,
      b.quarter,
      b.status,
    ]);

    const csvContent = headers.join(',') + '\n' + rows.map(r => r.join(',')).join('\n') + '\n';
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `master_budget_expenditure_${financialYear.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    addToast(
      'Full Ledger Exported',
      `Master budget and expenditure ledger (${budgets.length} entries) exported to CSV.`,
      'SUCCESS'
    );
  };

  const handleDownloadSignedPDF = (r: ReportItem) => {
    try {
      generateSignedReportPDF(r, {
        ...printOptions,
        signatoryName: user?.name || 'Dr. Rajeshwar Rao, IAS',
        signatoryRole: user?.designation || 'Joint Secretary & Financial Advisor, MoF',
      });
      addToast(
        'Signed PDF Downloaded',
        `Official dossier "${r.title}" compiled and cryptographically attested on client side.`,
        'SUCCESS'
      );
    } catch (err: any) {
      console.error('PDF Generation failed:', err);
      addToast('PDF Export Error', 'Failed to compile client-side PDF dossier.', 'ERROR');
    }
  };

  const handlePrint = () => {
    window.print();
    addToast(
      'Print / PDF Export Initiated',
      'Dossier formatted according to government documentation standards.',
      'INFO'
    );
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
            Executive Financial Reports & Audit Dossiers
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Generate analytical dossiers with integrated AI executive summaries, CAG audit annexures, and scheme outcomes.
          </p>
        </div>

        <button
          id="btn-export-full-ledger-csv"
          onClick={handleExportFullLedgerCSV}
          className="flex items-center gap-1.5 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-semibold shadow-xs transition-colors self-start sm:self-auto"
        >
          <FileSpreadsheet className="w-3.5 h-3.5" />
          <span>Export Master Ledger (CSV)</span>
        </button>
      </div>

      {/* Generator Form Card */}
      <div className="p-5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
        <div className="flex items-center gap-2 mb-3">
          <Sparkles className="w-4 h-4 text-blue-600 dark:text-blue-400" />
          <h2 className="font-bold text-sm text-slate-900 dark:text-white">
            Generate Official Evaluation Dossier
          </h2>
        </div>

        <form onSubmit={handleGenerate} className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
          <div>
            <label className="block font-medium text-slate-700 dark:text-slate-300 mb-1">
              Report Framework
            </label>
            <select
              value={reportType}
              onChange={e => setReportType(e.target.value as any)}
              className="w-full p-2 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:outline-none"
            >
              <option value="MONTHLY_UTILIZATION">Monthly Utilization Summary</option>
              <option value="ANOMALY_SUMMARY">AI Anomaly & Risk Dossier</option>
              <option value="AUDIT_COMPLIANCE">CAG Compliance & GFR Register</option>
              <option value="SCHEME_EVALUATION">Scheme Delivery Evaluation</option>
            </select>
          </div>

          <div>
            <label className="block font-medium text-slate-700 dark:text-slate-300 mb-1">
              Department Scope
            </label>
            <select
              value={departmentName}
              onChange={e => setDepartmentName(e.target.value)}
              className="w-full p-2 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:outline-none"
            >
              <option value="All Departments">All Government Departments (Union Level)</option>
              {departments.map(d => (
                <option key={d.id} value={d.name}>
                  {d.name}
                </option>
              ))}
            </select>
          </div>

          <div className="flex items-end">
            <button
              id="btn-submit-generate-report"
              type="submit"
              disabled={isGenerating}
              className="w-full py-2 px-4 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-semibold flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
            >
              <FileSpreadsheet className="w-4 h-4" />
              <span>{isGenerating ? 'Synthesizing...' : 'Compile & Generate'}</span>
            </button>
          </div>
        </form>
      </div>

      {/* Available Reports Library */}
      <div className="space-y-3">
        <h3 className="font-bold text-xs text-slate-500 uppercase tracking-wider">
          Compiled Official Dossiers
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.map(r => (
            <div
              key={r.id}
              className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col justify-between"
            >
              <div>
                <div className="flex items-start justify-between gap-2 mb-2">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-lg bg-blue-100 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                      <FileText className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-xs text-slate-900 dark:text-white line-clamp-1">
                        {r.title}
                      </h4>
                      <p className="text-[10px] text-slate-400">
                        {r.departmentName} • FY {r.financialYear}
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 font-semibold whitespace-nowrap">
                    {r.status}
                  </span>
                </div>

                <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-850 border border-slate-100 dark:border-slate-800 text-[11px] text-slate-600 dark:text-slate-300 mb-3">
                  <span className="font-semibold text-blue-600 dark:text-blue-400 block mb-0.5">
                    AI Executive Finding:
                  </span>
                  <p className="line-clamp-2">{r.aiExecutiveSummary}</p>
                </div>
              </div>

              <div className="flex items-center justify-between text-[11px] text-slate-500 pt-2 border-t border-slate-100 dark:border-slate-800">
                <span>Compiled: {r.generatedAt}</span>
                <div className="flex items-center gap-2">
                  <button
                    id={`btn-download-signed-pdf-${r.id}`}
                    onClick={() => handleDownloadSignedPDF(r)}
                    className="flex items-center gap-1 text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 font-semibold transition-colors"
                    title="Generate Signed PDF Directly (Client-Side)"
                  >
                    <FileCheck2 className="w-3.5 h-3.5" />
                    <span>Signed PDF</span>
                  </button>
                  <button
                    id={`btn-download-csv-${r.id}`}
                    onClick={() => handleDownloadCSV(r)}
                    className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400 hover:text-emerald-500 font-semibold transition-colors"
                    title="Download Report CSV"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>CSV</span>
                  </button>
                  <button
                    id={`btn-view-dossier-${r.id}`}
                    onClick={() => setSelectedReport(r)}
                    className="text-blue-600 dark:text-blue-400 font-semibold hover:underline"
                  >
                    View Dossier →
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Official Dossier View Modal */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl w-full max-w-4xl max-h-[92vh] flex flex-col overflow-hidden print:p-0 print:border-none print:shadow-none print:max-w-none print:h-auto print:max-h-none">
            {/* Modal Action Header */}
            <div className="p-4 sm:p-5 border-b border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3 print:hidden">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                  <FileText className="w-4 h-4" />
                </div>
                <div>
                  <h2 className="font-bold text-sm text-slate-900 dark:text-white">
                    Executive Dossier Preview
                  </h2>
                  <p className="text-[11px] text-slate-500">
                    {selectedReport.title} • {selectedReport.financialYear}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  id="btn-toggle-print-options-panel"
                  onClick={() => setShowPrintOptions(!showPrintOptions)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 border transition-all ${
                    showPrintOptions
                      ? 'bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 border-blue-300 dark:border-blue-800'
                      : 'bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 border-slate-200 dark:border-slate-700'
                  }`}
                >
                  <Sliders className="w-3.5 h-3.5 text-blue-600 dark:text-blue-400" />
                  <span>Print Options</span>
                </button>

                <button
                  id="btn-modal-download-signed-pdf"
                  type="button"
                  onClick={() => handleDownloadSignedPDF(selectedReport)}
                  className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-bold flex items-center gap-1.5 shadow-xs transition-colors cursor-pointer"
                  title="Direct Client-Side Signed PDF (Bypasses Browser Printing)"
                >
                  <FileCheck2 className="w-3.5 h-3.5" />
                  <span>Generate Signed PDF</span>
                </button>

                <button
                  id="btn-modal-download-csv"
                  onClick={() => handleDownloadCSV(selectedReport)}
                  className="px-3 py-1.5 bg-emerald-50 dark:bg-emerald-950/60 hover:bg-emerald-100 text-emerald-700 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>CSV</span>
                </button>

                <button
                  id="btn-modal-print-pdf"
                  onClick={handlePrint}
                  className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
                  title="Native Browser Print"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Print View</span>
                </button>

                <button
                  onClick={() => setSelectedReport(null)}
                  className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Print Options Configuration Panel */}
            {showPrintOptions && (
              <div className="bg-slate-50 dark:bg-slate-850 p-4 border-b border-slate-200 dark:border-slate-800 print:hidden space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Sliders className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                    <span className="font-bold text-xs text-slate-800 dark:text-slate-200">
                      Configure Printable Sections & Layout
                    </span>
                    <span className="text-[10px] text-slate-500">
                      (Toggle sections before sending to printer or exporting PDF)
                    </span>
                  </div>

                  {/* Preset Quick Actions */}
                  <div className="flex items-center gap-1.5 text-[11px]">
                    <span className="text-slate-400 font-medium mr-1">Presets:</span>
                    <button
                      type="button"
                      onClick={() => applyPrintPreset('ALL')}
                      className="px-2 py-0.5 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 font-semibold"
                    >
                      All Sections
                    </button>
                    <button
                      type="button"
                      onClick={() => applyPrintPreset('CHARTS_ONLY')}
                      className="px-2 py-0.5 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 font-semibold flex items-center gap-1"
                    >
                      <BarChart3 className="w-3 h-3 text-indigo-500" />
                      Charts Only
                    </button>
                    <button
                      type="button"
                      onClick={() => applyPrintPreset('TABLES_ONLY')}
                      className="px-2 py-0.5 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 font-semibold flex items-center gap-1"
                    >
                      <Table className="w-3 h-3 text-emerald-500" />
                      Tables Only
                    </button>
                    <button
                      type="button"
                      onClick={() => applyPrintPreset('EXECUTIVE_BRIEF')}
                      className="px-2 py-0.5 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 font-semibold"
                    >
                      Briefing
                    </button>
                  </div>
                </div>

                {/* Section Toggle Grid */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeLetterhead}
                      onChange={() => togglePrintOption('includeLetterhead')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Letterhead & Seal
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeMetadata}
                      onChange={() => togglePrintOption('includeMetadata')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Authority Metadata
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeAISummary}
                      onChange={() => togglePrintOption('includeAISummary')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      AI Executive Summary
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeVisualCharts}
                      onChange={() => togglePrintOption('includeVisualCharts')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Visual Charts
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeSectorTables}
                      onChange={() => togglePrintOption('includeSectorTables')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Sector Aggregates Table
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeSchemeLedger}
                      onChange={() => togglePrintOption('includeSchemeLedger')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Scheme Ledger Table
                    </span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700/80 cursor-pointer hover:border-blue-400 transition-colors">
                    <input
                      type="checkbox"
                      checked={printOptions.includeSignatory}
                      onChange={() => togglePrintOption('includeSignatory')}
                      className="rounded text-blue-600 focus:ring-0"
                    />
                    <span className="font-medium text-slate-700 dark:text-slate-200 text-[11px]">
                      Signatory & Seal
                    </span>
                  </label>

                  <div className="flex items-center justify-end">
                    <span className="text-[10px] text-slate-400 italic">
                      Live document preview updates below
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Printable Report Document */}
            <div className="flex-1 overflow-y-auto p-8 space-y-6 text-slate-800 dark:text-slate-200 text-xs print:p-0 print:overflow-visible">
              {/* Document Letterhead */}
              {printOptions.includeLetterhead && (
                <div className="text-center border-b pb-4 border-slate-200 dark:border-slate-800 space-y-1">
                  <p className="text-[10px] tracking-widest uppercase font-bold text-slate-500">
                    GOVERNMENT OF INDIA • MINISTRY OF FINANCE
                  </p>
                  <h1 className="text-lg font-extrabold text-slate-900 dark:text-white">
                    BUDGET UTILIZATION & EXPENDITURE MONITORING DOSSIER
                  </h1>
                  <p className="text-[11px] text-slate-500">
                    Framework: GFR 2017 • Financial Year: {selectedReport.financialYear}
                  </p>
                </div>
              )}

              {/* Metadata Table */}
              {printOptions.includeMetadata && (
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 dark:bg-slate-850 p-3.5 rounded-xl border border-slate-200 dark:border-slate-700">
                  <div>
                    <span className="text-[10px] text-slate-400 block">Department</span>
                    <span className="font-semibold text-slate-900 dark:text-white">
                      {selectedReport.departmentName}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block">Report Type</span>
                    <span className="font-semibold text-slate-900 dark:text-white">
                      {(selectedReport.reportType || '').replace(/_/g, ' ')}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block">Compiled By</span>
                    <span className="font-semibold text-slate-900 dark:text-white">
                      {selectedReport.generatedBy}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block">Generated Date</span>
                    <span className="font-semibold text-slate-900 dark:text-white">
                      {selectedReport.generatedAt}
                    </span>
                  </div>
                </div>
              )}

              {/* AI Executive Summary Block */}
              {printOptions.includeAISummary && (
                <div className="p-4 rounded-xl bg-blue-50/70 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900/60 space-y-1.5">
                  <div className="flex items-center gap-1.5 font-bold text-blue-900 dark:text-blue-300">
                    <Sparkles className="w-4 h-4 text-amber-500" />
                    <span>Executive Analytical Summary</span>
                  </div>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-xs">
                    {selectedReport.aiExecutiveSummary}
                  </p>
                </div>
              )}

              {/* Visual Charts & Outlay Trajectory Section */}
              {printOptions.includeVisualCharts && (
                <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3">
                  <div className="flex items-center justify-between border-b pb-2 border-slate-100 dark:border-slate-800">
                    <h3 className="font-bold text-xs uppercase tracking-wider text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                      <BarChart3 className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" />
                      Fiscal Absorption & Outlay Comparison (Visual)
                    </h3>
                    <span className="text-[10px] text-slate-400">Figures in ₹ Crores</span>
                  </div>

                  <div className="space-y-3 pt-1">
                    {/* Revenue Expenditure Bar */}
                    <div>
                      <div className="flex items-center justify-between text-xs mb-1">
                        <span className="font-semibold text-slate-800 dark:text-slate-200">
                          Revenue Expenditure: ₹8,450.0 Cr / ₹11,200.0 Cr
                        </span>
                        <span className="font-bold text-emerald-600">75.4% Absorbed</span>
                      </div>
                      <div className="w-full h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden border border-slate-200 dark:border-slate-700">
                        <div
                          className="h-full bg-emerald-500 rounded-full"
                          style={{ width: '75.4%' }}
                        />
                      </div>
                    </div>

                    {/* Capital Outlay Bar */}
                    <div>
                      <div className="flex items-center justify-between text-xs mb-1">
                        <span className="font-semibold text-slate-800 dark:text-slate-200">
                          Capital Outlays: ₹4,760.0 Cr / ₹7,250.0 Cr
                        </span>
                        <span className="font-bold text-blue-600">65.6% Absorbed</span>
                      </div>
                      <div className="w-full h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden border border-slate-200 dark:border-slate-700">
                        <div
                          className="h-full bg-blue-500 rounded-full"
                          style={{ width: '65.6%' }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Monitored Sector Aggregates Table */}
              {printOptions.includeSectorTables && (
                <div>
                  <h3 className="font-bold text-xs uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-2 flex items-center gap-1.5">
                    <Table className="w-3.5 h-3.5 text-slate-500" />
                    Monitored Sector Aggregates
                  </h3>
                  <table className="w-full text-left border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden">
                    <thead className="bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-400 text-[11px]">
                      <tr>
                        <th className="p-2.5 border-b">Parameter</th>
                        <th className="p-2.5 border-b">Approved Outlay</th>
                        <th className="p-2.5 border-b">Recorded Expenditure</th>
                        <th className="p-2.5 border-b">Absorption Velocity</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-xs">
                      <tr>
                        <td className="p-2.5 font-medium">Revenue Expenditure</td>
                        <td className="p-2.5">₹11,200.0 Cr</td>
                        <td className="p-2.5">₹8,450.0 Cr</td>
                        <td className="p-2.5 text-emerald-600 font-bold">75.4%</td>
                      </tr>
                      <tr>
                        <td className="p-2.5 font-medium">Capital Outlays (Infrastructure)</td>
                        <td className="p-2.5">₹7,250.0 Cr</td>
                        <td className="p-2.5">₹4,760.0 Cr</td>
                        <td className="p-2.5 text-blue-600 font-bold">65.6%</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              )}

              {/* Detailed Scheme Ledger Table */}
              {printOptions.includeSchemeLedger && (
                <div>
                  <h3 className="font-bold text-xs uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-2 flex items-center gap-1.5">
                    <FileSpreadsheet className="w-3.5 h-3.5 text-slate-500" />
                    Scheme-Level Disbursement Ledger (Sample)
                  </h3>
                  <table className="w-full text-left border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden text-xs">
                    <thead className="bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-400 text-[11px]">
                      <tr>
                        <th className="p-2.5 border-b">Scheme / Programme</th>
                        <th className="p-2.5 border-b">GFR Head</th>
                        <th className="p-2.5 border-b">Allocated (Cr)</th>
                        <th className="p-2.5 border-b">Disbursed (Cr)</th>
                        <th className="p-2.5 border-b">Audit Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                      <tr>
                        <td className="p-2.5 font-medium">National Highway Corridor Expansion</td>
                        <td className="p-2.5 text-slate-500">5054 Capital</td>
                        <td className="p-2.5 font-semibold">₹4,200.0</td>
                        <td className="p-2.5 text-emerald-600 font-semibold">₹3,420.0</td>
                        <td className="p-2.5">
                          <span className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 text-[10px] font-bold">
                            Reconciled
                          </span>
                        </td>
                      </tr>
                      <tr>
                        <td className="p-2.5 font-medium">Primary Health Centre Modernization</td>
                        <td className="p-2.5 text-slate-500">2210 Revenue</td>
                        <td className="p-2.5 font-semibold">₹2,800.0</td>
                        <td className="p-2.5 text-blue-600 font-semibold">₹2,180.0</td>
                        <td className="p-2.5">
                          <span className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 text-[10px] font-bold">
                            Reconciled
                          </span>
                        </td>
                      </tr>
                      <tr>
                        <td className="p-2.5 font-medium">Digital Literacy & School Tech Labs</td>
                        <td className="p-2.5 text-slate-500">2202 Education</td>
                        <td className="p-2.5 font-semibold">₹1,950.0</td>
                        <td className="p-2.5 text-amber-600 font-semibold">₹1,120.0</td>
                        <td className="p-2.5">
                          <span className="px-1.5 py-0.5 rounded bg-amber-50 text-amber-700 text-[10px] font-bold">
                            Under Audit Review
                          </span>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              )}

              {/* Signatory Block */}
              {printOptions.includeSignatory && (
                <div className="pt-8 border-t border-slate-200 dark:border-slate-800 flex justify-between items-end">
                  <div className="text-[10px] text-slate-400 space-y-0.5">
                    <p>Document Security: GOV-RESTRICTED • GFR COMPLIANT</p>
                    <p>Digital Cryptographic Hash: SHA256:9f83ae410b2849...gov</p>
                  </div>
                  <div className="text-right">
                    <div className="w-36 border-b border-slate-400 mb-1 inline-block" />
                    <p className="font-bold text-slate-800 dark:text-slate-200">
                      Joint Secretary & Financial Advisor
                    </p>
                    <p className="text-[10px] text-slate-400">Authorized Signatory</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
